# @package _global_

defaults:
  - _self_
  - data: default
  - trainer: default
  - model: visual_hull
  - experiment: null
  - callbacks: default

ckpt_path: null
default_root_dir: checkpoints/

task_name: "train"
tags: ["dev"]

train: True
test: False

seed: 1337